# Generated by Django 5.0.3 on 2024-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='img',
            field=models.ImageField(upload_to='products'),
        ),
    ]
